highlight-font: '"Avenir Next", "Helvetica Neue", Helvetica, Arial, sans-serif;'

body: '"Helvetica Neue", Helvetica, "Arial", san-serif'
code: '"Menlo", "Monaco", "Consolas", "Courier New", monospace'

highlight-color: '#DD4A38'
highlight-dark-color: '#B03B2C'

darker-color: '#9EA7B1'
darker-dark-color: '#7E858D'

background-color: '#FFFFFF'
alt-link-color: '#2F79E7'
warning-color: '#DD9C38'
