//
//  LVCAmazonS3Bucket.m
//  LayerVaultAPIClient
//
//  Created by Matt Thomas on 2/13/14.
//  Copyright (c) 2014 LayerVault. All rights reserved.
//

#import "LVCAmazonS3Bucket.h"

NSString *const LVCAmazonS3BucketDefault = @"omnivore-scratch";
NSString *const LVCAmazonS3BucketEU = @"omnivore-scratch-eu";
NSString *const LVCAmazonS3BucketWest = @"omnivore-scratch-west";
NSString *const LVCAmazonS3BucketBrazil = @"omnivore-scratch-brazil";
NSString *const LVCAmazonS3BucketSingapore = @"omnivore-scratch-singapore";
NSString *const LVCAmazonS3BucketJapan = @"omnivore-scratch-japan";
NSString *const LVCAmazonS3BucketAustralia = @"omnivore-scratch-australia";

static NSDictionary *timeZoneIDToHost(void)
{
    return @{@"Africa/Abidjan" : @"omnivore-scratch-eu",
             @"Africa/Accra" : @"omnivore-scratch-eu",
             @"Africa/Addis_Ababa" : @"omnivore-scratch-eu",
             @"Africa/Algiers" : @"omnivore-scratch-eu",
             @"Africa/Asmara" : @"omnivore-scratch-eu",
             @"Africa/Bamako" : @"omnivore-scratch-eu",
             @"Africa/Bangui" : @"omnivore-scratch-eu",
             @"Africa/Banjul" : @"omnivore-scratch-eu",
             @"Africa/Bissau" : @"omnivore-scratch-eu",
             @"Africa/Blantyre" : @"omnivore-scratch-eu",
             @"Africa/Brazzaville" : @"omnivore-scratch-eu",
             @"Africa/Bujumbura" : @"omnivore-scratch-eu",
             @"Africa/Cairo" : @"omnivore-scratch-eu",
             @"Africa/Casablanca" : @"omnivore-scratch-eu",
             @"Africa/Ceuta" : @"omnivore-scratch-eu",
             @"Africa/Conakry" : @"omnivore-scratch-eu",
             @"Africa/Dakar" : @"omnivore-scratch-eu",
             @"Africa/Dar_es_Salaam" : @"omnivore-scratch-eu",
             @"Africa/Djibouti" : @"omnivore-scratch-eu",
             @"Africa/Douala" : @"omnivore-scratch-eu",
             @"Africa/El_Aaiun" : @"omnivore-scratch-eu",
             @"Africa/Freetown" : @"omnivore-scratch-eu",
             @"Africa/Gaborone" : @"omnivore-scratch-eu",
             @"Africa/Harare" : @"omnivore-scratch-eu",
             @"Africa/Johannesburg" : @"omnivore-scratch-eu",
             @"Africa/Juba" : @"omnivore-scratch-eu",
             @"America/Adak" : @"omnivore-scratch-west",
             @"America/Anchorage" : @"omnivore-scratch-west",
             @"America/Anguilla" : @"omnivore-scratch",
             @"America/Antigua" : @"omnivore-scratch",
             @"America/Araguaina" : @"omnivore-scratch-brazil",
             @"America/Argentina/Buenos_Aires" : @"omnivore-scratch-brazil",
             @"America/Argentina/Catamarca" : @"omnivore-scratch-brazil",
             @"America/Argentina/Cordoba" : @"omnivore-scratch-brazil",
             @"America/Argentina/Jujuy" : @"omnivore-scratch-brazil",
             @"America/Argentina/La_Rioja" : @"omnivore-scratch-brazil",
             @"America/Argentina/Mendoza" : @"omnivore-scratch-brazil",
             @"America/Argentina/Rio_Gallegos" : @"omnivore-scratch-brazil",
             @"America/Argentina/Salta" : @"omnivore-scratch-brazil",
             @"America/Argentina/San_Juan" : @"omnivore-scratch-brazil",
             @"America/Argentina/San_Luis" : @"omnivore-scratch-brazil",
             @"America/Argentina/Tucuman" : @"omnivore-scratch-brazil",
             @"America/Argentina/Ushuaia" : @"omnivore-scratch-brazil",
             @"America/Aruba" : @"omnivore-scratch",
             @"America/Asuncion" : @"omnivore-scratch-brazil",
             @"America/Atikokan" : @"omnivore-scratch",
             @"America/Bahia" : @"omnivore-scratch-brazil",
             @"America/Bahia_Banderas" : @"omnivore-scratch-brazil",
             @"America/Barbados" : @"omnivore-scratch",
             @"America/Belem" : @"omnivore-scratch-brazil",
             @"America/Belize" : @"omnivore-scratch",
             @"America/Blanc-Sablon" : @"omnivore-scratch",
             @"America/Boa_Vista" : @"omnivore-scratch-brazil",
             @"America/Bogota" : @"omnivore-scratch-brazil",
             @"America/Boise" : @"omnivore-scratch-west",
             @"America/Cambridge_Bay" : @"omnivore-scratch-west",
             @"America/Campo_Grande" : @"omnivore-scratch-brazil",
             @"America/Cancun" : @"omnivore-scratch-west",
             @"America/Caracas" : @"omnivore-scratch-brazil",
             @"America/Cayenne" : @"omnivore-scratch-brazil",
             @"America/Cayman" : @"omnivore-scratch",
             @"America/Chicago" : @"omnivore-scratch",
             @"America/Chihuahua" : @"omnivore-scratch",
             @"America/Costa_Rica" : @"omnivore-scratch",
             @"America/Creston" : @"omnivore-scratch-west",
             @"America/Cuiaba" : @"omnivore-scratch-brazil",
             @"America/Curacao" : @"omnivore-scratch-brazil",
             @"America/Danmarkshavn" : @"omnivore-scratch",
             @"America/Dawson" : @"omnivore-scratch-west",
             @"America/Dawson_Creek" : @"omnivore-scratch-west",
             @"America/Denver" : @"omnivore-scratch-west",
             @"America/Detroit" : @"omnivore-scratch",
             @"America/Dominica" : @"omnivore-scratch",
             @"America/Edmonton" : @"omnivore-scratch-west",
             @"America/Eirunepe" : @"omnivore-scratch-brazil",
             @"America/El_Salvador" : @"omnivore-scratch",
             @"America/Fortaleza" : @"omnivore-scratch-brazil",
             @"America/Glace_Bay" : @"omnivore-scratch",
             @"America/Godthab" : @"omnivore-scratch",
             @"America/Goose_Bay" : @"omnivore-scratch",
             @"America/Grand_Turk" : @"omnivore-scratch",
             @"America/Grenada" : @"omnivore-scratch-brazil",
             @"America/Guadeloupe" : @"omnivore-scratch-brazil",
             @"America/Guatemala" : @"omnivore-scratch-west",
             @"America/Guayaquil" : @"omnivore-scratch-brazil",
             @"America/Guyana" : @"omnivore-scratch-brazil",
             @"America/Halifax" : @"omnivore-scratch",
             @"America/Havana" : @"omnivore-scratch",
             @"America/Hermosillo" : @"omnivore-scratch-west",
             @"America/Indiana/Indianapolis" : @"omnivore-scratch",
             @"America/Indiana/Knox" : @"omnivore-scratch",
             @"America/Indiana/Marengo" : @"omnivore-scratch",
             @"America/Indiana/Petersburg" : @"omnivore-scratch",
             @"America/Indiana/Tell_City" : @"omnivore-scratch",
             @"America/Indiana/Vevay" : @"omnivore-scratch",
             @"America/Indiana/Vincennes" : @"omnivore-scratch",
             @"America/Indiana/Winamac" : @"omnivore-scratch",
             @"America/Inuvik" : @"omnivore-scratch-west",
             @"America/Iqaluit" : @"omnivore-scratch",
             @"America/Jamaica" : @"omnivore-scratch",
             @"America/Juneau" : @"omnivore-scratch-west",
             @"America/Kentucky/Louisville" : @"omnivore-scratch",
             @"America/Kentucky/Monticello" : @"omnivore-scratch",
             @"America/Kralendijk" : @"omnivore-scratch-brazil",
             @"America/La_Paz" : @"omnivore-scratch-brazil",
             @"America/Lima" : @"omnivore-scratch-brazil",
             @"America/Los_Angeles" : @"omnivore-scratch-west",
             @"America/Lower_Princes" : @"omnivore-scratch",
             @"America/Maceio" : @"omnivore-scratch-brazil",
             @"America/Managua" : @"omnivore-scratch-west",
             @"America/Manaus" : @"omnivore-scratch-brazil",
             @"America/Marigot" : @"omnivore-scratch",
             @"America/Martinique" : @"omnivore-scratch",
             @"America/Matamoros" : @"omnivore-scratch-west",
             @"America/Mazatlan" : @"omnivore-scratch-west",
             @"America/Menominee" : @"omnivore-scratch",
             @"America/Merida" : @"omnivore-scratch-west",
             @"America/Metlakatla" : @"omnivore-scratch-west",
             @"America/Mexico_City" : @"omnivore-scratch-west",
             @"America/Miquelon" : @"omnivore-scratch",
             @"America/Moncton" : @"omnivore-scratch",
             @"America/Monterrey" : @"omnivore-scratch-west",
             @"America/Montevideo" : @"omnivore-scratch-brazil",
             @"America/Montreal" : @"omnivore-scratch",
             @"America/Montserrat" : @"omnivore-scratch",
             @"America/Nassau" : @"omnivore-scratch",
             @"America/New_York" : @"omnivore-scratch",
             @"America/Nipigon" : @"omnivore-scratch-",
             @"America/Nome" : @"omnivore-scratch-west",
             @"America/Noronha" : @"omnivore-scratch-brazil",
             @"America/North_Dakota/Beulah" : @"omnivore-scratch-west",
             @"America/North_Dakota/Center" : @"omnivore-scratch-west",
             @"America/North_Dakota/New_Salem" : @"omnivore-scratch-west",
             @"America/Ojinaga" : @"omnivore-scratch-west",
             @"America/Panama" : @"omnivore-scratch-brazil",
             @"America/Pangnirtung" : @"omnivore-scratch",
             @"America/Paramaribo" : @"omnivore-scratch-brazil",
             @"America/Phoenix" : @"omnivore-scratch-west",
             @"America/Port-au-Prince" : @"omnivore-scratch",
             @"America/Port_of_Spain" : @"omnivore-scratch-brazil",
             @"America/Porto_Velho" : @"omnivore-scratch-brazil",
             @"America/Puerto_Rico" : @"omnivore-scratch",
             @"America/Rainy_River" : @"omnivore-scratch-west",
             @"America/Rankin_Inlet" : @"omnivore-scratch-west",
             @"America/Recife" : @"omnivore-scratch-brazil",
             @"America/Regina" : @"omnivore-scratch-west",
             @"America/Resolute" : @"omnivore-scratch-west",
             @"America/Rio_Branco" : @"omnivore-scratch-brazil",
             @"America/Santa_Isabel" : @"omnivore-scratch-west",
             @"America/Santarem" : @"omnivore-scratch-brazil",
             @"America/Santiago" : @"omnivore-scratch-brazil",
             @"America/Santo_Domingo" : @"omnivore-scratch",
             @"America/Sao_Paulo" : @"omnivore-scratch-brazil",
             @"America/St_Kitts" : @"omnivore-scratch",
             @"America/St_Lucia" : @"omnivore-scratch",
             @"America/St_Thomas" : @"omnivore-scratch",
             @"America/St_Vincent" : @"omnivore-scratch",
             @"America/Swift_Current" : @"omnivore-scratch-west",
             @"America/Tegucigalpa" : @"omnivore-scratch-west",
             @"America/Thule" : @"omnivore-scratch",
             @"America/Thunder_Bay" : @"omnivore-scratch",
             @"America/Tijuana" : @"omnivore-scratch-west",
             @"America/Toronto" : @"omnivore-scratch",
             @"America/Tortola" : @"omnivore-scratch",
             @"America/Vancouver" : @"omnivore-scratch-west",
             @"America/Whitehorse" : @"omnivore-scratch-west",
             @"America/Winnipeg" : @"omnivore-scratch",
             @"America/Yakutat" : @"omnivore-scratch-west",
             @"America/Yellowknife" : @"omnivore-scratch-west",
             @"Antarctica/Casey" : @"omnivore-scratch-brazil",
             @"Antarctica/Davis" : @"omnivore-scratch-brazil",
             @"Antarctica/DumontDUrville" : @"omnivore-scratch-brazil",
             @"Antarctica/Macquarie" : @"omnivore-scratch-brazil",
             @"Antarctica/Mawson" : @"omnivore-scratch-brazil",
             @"Antarctica/McMurdo" : @"omnivore-scratch-brazil",
             @"Antarctica/Palmer" : @"omnivore-scratch-brazil",
             @"Antarctica/Rothera" : @"omnivore-scratch-brazil",
             @"Antarctica/South_Pole" : @"omnivore-scratch-brazil",
             @"Antarctica/Syowa" : @"omnivore-scratch-brazil",
             @"Antarctica/Vostok" : @"omnivore-scratch-brazil",
             @"Arctic/Longyearbyen" : @"omnivore-scratch-brazil",
             @"Asia/Aden" : @"omnivore-scratch-singapore",
             @"Asia/Almaty" : @"omnivore-scratch-singapore",
             @"Asia/Amman" : @"omnivore-scratch-singapore",
             @"Asia/Anadyr" : @"omnivore-scratch-singapore",
             @"Asia/Aqtau" : @"omnivore-scratch-singapore",
             @"Asia/Aqtobe" : @"omnivore-scratch-singapore",
             @"Asia/Ashgabat" : @"omnivore-scratch-singapore",
             @"Asia/Baghdad" : @"omnivore-scratch-singapore",
             @"Asia/Bahrain" : @"omnivore-scratch-singapore",
             @"Asia/Baku" : @"omnivore-scratch-singapore",
             @"Asia/Bangkok" : @"omnivore-scratch-singapore",
             @"Asia/Beirut" : @"omnivore-scratch-singapore",
             @"Asia/Bishkek" : @"omnivore-scratch-singapore",
             @"Asia/Brunei" : @"omnivore-scratch-singapore",
             @"Asia/Choibalsan" : @"omnivore-scratch-singapore",
             @"Asia/Chongqing" : @"omnivore-scratch-singapore",
             @"Asia/Colombo" : @"omnivore-scratch-singapore",
             @"Asia/Damascus" : @"omnivore-scratch-singapore",
             @"Asia/Dhaka" : @"omnivore-scratch-singapore",
             @"Asia/Dili" : @"omnivore-scratch-singapore",
             @"Asia/Dubai" : @"omnivore-scratch-singapore",
             @"Asia/Dushanbe" : @"omnivore-scratch-singapore",
             @"Asia/Gaza" : @"omnivore-scratch-singapore",
             @"Asia/Harbin" : @"omnivore-scratch-singapore",
             @"Asia/Hebron" : @"omnivore-scratch-singapore",
             @"Asia/Ho_Chi_Minh" : @"omnivore-scratch-singapore",
             @"Asia/Hong_Kong" : @"omnivore-scratch-singapore",
             @"Asia/Hovd" : @"omnivore-scratch-singapore",
             @"Asia/Irkutsk" : @"omnivore-scratch-singapore",
             @"Asia/Jakarta" : @"omnivore-scratch-singapore",
             @"Asia/Jayapura" : @"omnivore-scratch-singapore",
             @"Asia/Jerusalem" : @"omnivore-scratch-singapore",
             @"Asia/Kabul" : @"omnivore-scratch-singapore",
             @"Asia/Kamchatka" : @"omnivore-scratch-singapore",
             @"Asia/Karachi" : @"omnivore-scratch-singapore",
             @"Asia/Kashgar" : @"omnivore-scratch-singapore",
             @"Asia/Kathmandu" : @"omnivore-scratch-singapore",
             @"Asia/Katmandu" : @"omnivore-scratch-singapore",
             @"Asia/Khandyga" : @"omnivore-scratch-singapore",
             @"Asia/Kolkata" : @"omnivore-scratch-singapore",
             @"Asia/Krasnoyarsk" : @"omnivore-scratch-singapore",
             @"Asia/Kuala_Lumpur" : @"omnivore-scratch-singapore",
             @"Asia/Kuching" : @"omnivore-scratch-singapore",
             @"Asia/Kuwait" : @"omnivore-scratch-singapore",
             @"Asia/Macau" : @"omnivore-scratch-singapore",
             @"Asia/Magadan" : @"omnivore-scratch-singapore",
             @"Asia/Makassar" : @"omnivore-scratch-singapore",
             @"Asia/Manila" : @"omnivore-scratch-singapore",
             @"Asia/Muscat" : @"omnivore-scratch-singapore",
             @"Asia/Nicosia" : @"omnivore-scratch-singapore",
             @"Asia/Novokuznetsk" : @"omnivore-scratch-singapore",
             @"Asia/Novosibirsk" : @"omnivore-scratch-singapore",
             @"Asia/Omsk" : @"omnivore-scratch-singapore",
             @"Asia/Oral" : @"omnivore-scratch-singapore",
             @"Asia/Phnom_Penh" : @"omnivore-scratch-singapore",
             @"Asia/Pontianak" : @"omnivore-scratch-singapore",
             @"Asia/Pyongyang" : @"omnivore-scratch-singapore",
             @"Asia/Qatar" : @"omnivore-scratch-singapore",
             @"Asia/Qyzylorda" : @"omnivore-scratch-singapore",
             @"Asia/Rangoon" : @"omnivore-scratch-singapore",
             @"Asia/Riyadh" : @"omnivore-scratch-singapore",
             @"Asia/Sakhalin" : @"omnivore-scratch-singapore",
             @"Asia/Samarkand" : @"omnivore-scratch-singapore",
             @"Asia/Seoul" : @"omnivore-scratch-japan",
             @"Asia/Shanghai" : @"omnivore-scratch-singapore",
             @"Asia/Singapore" : @"omnivore-scratch-singapore",
             @"Asia/Taipei" : @"omnivore-scratch-singapore",
             @"Asia/Tashkent" : @"omnivore-scratch-singapore",
             @"Asia/Tbilisi" : @"omnivore-scratch-singapore",
             @"Asia/Tehran" : @"omnivore-scratch-singapore",
             @"Asia/Thimphu" : @"omnivore-scratch-singapore",
             @"Asia/Tokyo" : @"omnivore-scratch-japan",
             @"Asia/Ulaanbaatar" : @"omnivore-scratch-singapore",
             @"Asia/Urumqi" : @"omnivore-scratch-singapore",
             @"Asia/Ust-Nera" : @"omnivore-scratch-singapore",
             @"Asia/Vientiane" : @"omnivore-scratch-singapore",
             @"Asia/Vladivostok" : @"omnivore-scratch-singapore",
             @"Asia/Yakutsk" : @"omnivore-scratch-singapore",
             @"Asia/Yekaterinburg" : @"omnivore-scratch-singapore",
             @"Asia/Yerevan" : @"omnivore-scratch-singapore",
             @"Atlantic/Azores" : @"omnivore-scratch",
             @"Atlantic/Bermuda" : @"omnivore-scratch",
             @"Atlantic/Canary" : @"omnivore-scratch-eu",
             @"Atlantic/Cape_Verde" : @"omnivore-scratch-eu",
             @"Atlantic/Faroe" : @"omnivore-scratch-eu",
             @"Atlantic/Madeira" : @"omnivore-scratch-eu",
             @"Atlantic/Reykjavik" : @"omnivore-scratch-eu",
             @"Atlantic/South_Georgia" : @"omnivore-scratch-brazil",
             @"Atlantic/St_Helena" : @"omnivore-scratch-eu",
             @"Atlantic/Stanley" : @"omnivore-scratch-brazil",
             @"Australia/Adelaide" : @"omnivore-scratch-australia",
             @"Australia/Brisbane" : @"omnivore-scratch-australia",
             @"Australia/Broken_Hill" : @"omnivore-scratch-australia",
             @"Australia/Currie" : @"omnivore-scratch-australia",
             @"Australia/Darwin" : @"omnivore-scratch-australia",
             @"Australia/Eucla" : @"omnivore-scratch-australia",
             @"Australia/Hobart" : @"omnivore-scratch-australia",
             @"Australia/Lindeman" : @"omnivore-scratch-australia",
             @"Australia/Lord_Howe" : @"omnivore-scratch-australia",
             @"Australia/Melbourne" : @"omnivore-scratch-australia",
             @"Australia/Perth" : @"omnivore-scratch-australia",
             @"Australia/Sydney" : @"omnivore-scratch-australia",
             @"Europe/Amsterdam" : @"omnivore-scratch-eu",
             @"Europe/Andorra" : @"omnivore-scratch-eu",
             @"Europe/Athens" : @"omnivore-scratch-eu",
             @"Europe/Belgrade" : @"omnivore-scratch-eu",
             @"Europe/Berlin" : @"omnivore-scratch-eu",
             @"Europe/Bratislava" : @"omnivore-scratch-eu",
             @"Europe/Brussels" : @"omnivore-scratch-eu",
             @"Europe/Bucharest" : @"omnivore-scratch-eu",
             @"Europe/Budapest" : @"omnivore-scratch-eu",
             @"Europe/Busingen" : @"omnivore-scratch-eu",
             @"Europe/Chisinau" : @"omnivore-scratch-eu",
             @"Europe/Copenhagen" : @"omnivore-scratch-eu",
             @"Europe/Dublin" : @"omnivore-scratch-eu",
             @"Europe/Gibraltar" : @"omnivore-scratch-eu",
             @"Europe/Guernsey" : @"omnivore-scratch-eu",
             @"Europe/Helsinki" : @"omnivore-scratch-eu",
             @"Europe/Isle_of_Man" : @"omnivore-scratch-eu",
             @"Europe/Istanbul" : @"omnivore-scratch-eu",
             @"Europe/Jersey" : @"omnivore-scratch-eu",
             @"Europe/Kaliningrad" : @"omnivore-scratch-eu",
             @"Europe/Kiev" : @"omnivore-scratch-eu",
             @"Europe/Lisbon" : @"omnivore-scratch-eu",
             @"Europe/Ljubljana" : @"omnivore-scratch-eu",
             @"Europe/London" : @"omnivore-scratch-eu",
             @"Europe/Luxembourg" : @"omnivore-scratch-eu",
             @"Europe/Madrid" : @"omnivore-scratch-eu",
             @"Europe/Malta" : @"omnivore-scratch-eu",
             @"Europe/Mariehamn" : @"omnivore-scratch-eu",
             @"Europe/Minsk" : @"omnivore-scratch-eu",
             @"Europe/Monaco" : @"omnivore-scratch-eu",
             @"Europe/Moscow" : @"omnivore-scratch-eu",
             @"Europe/Oslo" : @"omnivore-scratch-eu",
             @"Europe/Paris" : @"omnivore-scratch-eu",
             @"Europe/Podgorica" : @"omnivore-scratch-eu",
             @"Europe/Prague" : @"omnivore-scratch-eu",
             @"Europe/Riga" : @"omnivore-scratch-eu",
             @"Europe/Rome" : @"omnivore-scratch-eu",
             @"Europe/Samara" : @"omnivore-scratch-eu",
             @"Europe/San_Marino" : @"omnivore-scratch-eu",
             @"Europe/Sarajevo" : @"omnivore-scratch-eu",
             @"Europe/Simferopol" : @"omnivore-scratch-eu",
             @"Europe/Skopje" : @"omnivore-scratch-eu",
             @"Europe/Sofia" : @"omnivore-scratch-eu",
             @"Europe/Stockholm" : @"omnivore-scratch-eu",
             @"Europe/Tallinn" : @"omnivore-scratch-eu",
             @"Europe/Tirane" : @"omnivore-scratch-eu",
             @"Europe/Uzhgorod" : @"omnivore-scratch-eu",
             @"Europe/Vaduz" : @"omnivore-scratch-eu",
             @"Europe/Vatican" : @"omnivore-scratch-eu",
             @"Europe/Vienna" : @"omnivore-scratch-eu",
             @"Europe/Vilnius" : @"omnivore-scratch-eu",
             @"Europe/Volgograd" : @"omnivore-scratch-eu",
             @"Europe/Warsaw" : @"omnivore-scratch-eu",
             @"Europe/Zagreb" : @"omnivore-scratch-eu",
             @"Europe/Zaporozhye" : @"omnivore-scratch-eu",
             @"Europe/Zurich" : @"omnivore-scratch-eu",
             @"GMT" : @"omnivore-scratch-eu",
             @"Indian/Antananarivo" : @"omnivore-scratch-singapore",
             @"Indian/Chagos" : @"omnivore-scratch-singapore",
             @"Indian/Christmas" : @"omnivore-scratch-singapore",
             @"Indian/Cocos" : @"omnivore-scratch-singapore",
             @"Indian/Comoro" : @"omnivore-scratch-singapore",
             @"Indian/Kerguelen" : @"omnivore-scratch-singapore",
             @"Indian/Mahe" : @"omnivore-scratch-singapore",
             @"Indian/Maldives" : @"omnivore-scratch-singapore",
             @"Indian/Mauritius" : @"omnivore-scratch-singapore",
             @"Indian/Mayotte" : @"omnivore-scratch-singapore",
             @"Indian/Reunion" : @"omnivore-scratch-singapore",
             @"Pacific/Apia" : @"omnivore-scratch-japan",
             @"Pacific/Auckland" : @"omnivore-scratch-japan",
             @"Pacific/Chatham" : @"omnivore-scratch-japan",
             @"Pacific/Chuuk" : @"omnivore-scratch-japan",
             @"Pacific/Easter" : @"omnivore-scratch-japan",
             @"Pacific/Efate" : @"omnivore-scratch-japan",
             @"Pacific/Enderbury" : @"omnivore-scratch-japan",
             @"Pacific/Fakaofo" : @"omnivore-scratch-japan",
             @"Pacific/Fiji" : @"omnivore-scratch-japan",
             @"Pacific/Funafuti" : @"omnivore-scratch-japan",
             @"Pacific/Galapagos" : @"omnivore-scratch-japan",
             @"Pacific/Gambier" : @"omnivore-scratch-japan",
             @"Pacific/Guadalcanal" : @"omnivore-scratch-japan",
             @"Pacific/Guam" : @"omnivore-scratch-japan",
             @"Pacific/Honolulu" : @"omnivore-scratch-west",
             @"Pacific/Johnston" : @"omnivore-scratch-japan",
             @"Pacific/Kiritimati" : @"omnivore-scratch-japan",
             @"Pacific/Kosrae" : @"omnivore-scratch-japan",
             @"Pacific/Kwajalein" : @"omnivore-scratch-japan",
             @"Pacific/Majuro" : @"omnivore-scratch-japan",
             @"Pacific/Marquesas" : @"omnivore-scratch-japan",
             @"Pacific/Midway" : @"omnivore-scratch-japan",
             @"Pacific/Nauru" : @"omnivore-scratch-japan",
             @"Pacific/Niue" : @"omnivore-scratch-japan",
             @"Pacific/Norfolk" : @"omnivore-scratch-japan",
             @"Pacific/Noumea" : @"omnivore-scratch-japan",
             @"Pacific/Pago_Pago" : @"omnivore-scratch-japan",
             @"Pacific/Palau" : @"omnivore-scratch-japan",
             @"Pacific/Pitcairn" : @"omnivore-scratch-japan",
             @"Pacific/Pohnpei" : @"omnivore-scratch-japan",
             @"Pacific/Ponape" : @"omnivore-scratch-japan",
             @"Pacific/Port_Moresby" : @"omnivore-scratch-japan",
             @"Pacific/Rarotonga" : @"omnivore-scratch-japan",
             @"Pacific/Saipan" : @"omnivore-scratch-japan",
             @"Pacific/Tahiti" : @"omnivore-scratch-japan",
             @"Pacific/Tarawa" : @"omnivore-scratch-japan",
             @"Pacific/Tongatapu" : @"omnivore-scratch-japan",
             @"Pacific/Truk" : @"omnivore-scratch-japan",
             @"Pacific/Wake" : @"omnivore-scratch-japan",
             @"Pacific/Wallis": @"omnivore-scratch-japan"};

}

@implementation LVCAmazonS3Bucket

+ (NSURL *)baseURLForLocalTimezone
{
    return [self baseURLForTimezone:[NSTimeZone localTimeZone]];
}


+ (NSURL *)baseURLForTimezone:(NSTimeZone *)timeZone
{
    return [NSURL URLWithString:[NSString stringWithFormat:@"https://%@.s3.amazonaws.com", [self bucketForTimezone:timeZone]]];
}

+ (NSString *)bucketForLocalTimezone
{
    return [self bucketForTimezone:[NSTimeZone localTimeZone]];
}

+ (NSString *)bucketForTimezone:(NSTimeZone *)timeZone
{
    NSString *bucket = nil;
    if (timeZone.name.length > 0) {
        bucket = timeZoneIDToHost()[timeZone.name];
    }
    return bucket ?: LVCAmazonS3BucketDefault;
}

@end
