//
//  LVCAmazonS3Bucket.m
//  LayerVaultAPIClient
//
//  Created by Matt Thomas on 2/13/14.
//  Copyright (c) 2014 LayerVault. All rights reserved.
//

#import "LVCAmazonS3Bucket.h"

NSString *const LVCAmazonS3BucketDefault = @"omnivore-scratch";
NSString *const LVCAmazonS3BucketEU = @"omnivore-scratch-eu";
NSString *const LVCAmazonS3BucketWest = @"omnivore-scratch-west";
NSString *const LVCAmazonS3BucketBrazil = @"omnivore-scratch-brazil";
NSString *const LVCAmazonS3BucketSingapore = @"omnivore-scratch-singapore";
NSString *const LVCAmazonS3BucketJapan = @"omnivore-scratch-japan";
NSString *const LVCAmazonS3BucketAustralia = @"omnivore-scratch-australia";

static NSDictionary *timeZoneIDToHost(void)
{
    return @{@"Africa/Abidjan" : LVCAmazonS3BucketEU,
             @"Africa/Accra" : LVCAmazonS3BucketEU,
             @"Africa/Addis_Ababa" : LVCAmazonS3BucketEU,
             @"Africa/Algiers" : LVCAmazonS3BucketEU,
             @"Africa/Asmara" : LVCAmazonS3BucketEU,
             @"Africa/Bamako" : LVCAmazonS3BucketEU,
             @"Africa/Bangui" : LVCAmazonS3BucketEU,
             @"Africa/Banjul" : LVCAmazonS3BucketEU,
             @"Africa/Bissau" : LVCAmazonS3BucketEU,
             @"Africa/Blantyre" : LVCAmazonS3BucketEU,
             @"Africa/Brazzaville" : LVCAmazonS3BucketEU,
             @"Africa/Bujumbura" : LVCAmazonS3BucketEU,
             @"Africa/Cairo" : LVCAmazonS3BucketEU,
             @"Africa/Casablanca" : LVCAmazonS3BucketEU,
             @"Africa/Ceuta" : LVCAmazonS3BucketEU,
             @"Africa/Conakry" : LVCAmazonS3BucketEU,
             @"Africa/Dakar" : LVCAmazonS3BucketEU,
             @"Africa/Dar_es_Salaam" : LVCAmazonS3BucketEU,
             @"Africa/Djibouti" : LVCAmazonS3BucketEU,
             @"Africa/Douala" : LVCAmazonS3BucketEU,
             @"Africa/El_Aaiun" : LVCAmazonS3BucketEU,
             @"Africa/Freetown" : LVCAmazonS3BucketEU,
             @"Africa/Gaborone" : LVCAmazonS3BucketEU,
             @"Africa/Harare" : LVCAmazonS3BucketEU,
             @"Africa/Johannesburg" : LVCAmazonS3BucketEU,
             @"Africa/Juba" : LVCAmazonS3BucketEU,
             @"America/St_Kitts" : LVCAmazonS3BucketDefault,
             @"America/St_Lucia" : LVCAmazonS3BucketDefault,
             @"America/St_Thomas" : LVCAmazonS3BucketDefault,
             @"America/St_Vincent" : LVCAmazonS3BucketDefault,
             @"America/Swift_Current" : LVCAmazonS3BucketWest,
             @"America/Tegucigalpa" : LVCAmazonS3BucketWest,
             @"America/Thule" : LVCAmazonS3BucketDefault,
             @"America/Thunder_Bay" : LVCAmazonS3BucketDefault,
             @"America/Tijuana" : LVCAmazonS3BucketWest,
             @"America/Toronto" : LVCAmazonS3BucketDefault,
             @"America/Tortola" : LVCAmazonS3BucketDefault,
             @"America/Vancouver" : LVCAmazonS3BucketWest,
             @"America/Whitehorse" : LVCAmazonS3BucketWest,
             @"America/Winnipeg" : LVCAmazonS3BucketDefault,
             @"America/Yakutat" : LVCAmazonS3BucketWest,
             @"America/Yellowknife" : LVCAmazonS3BucketWest,
             @"Antarctica/Casey" : LVCAmazonS3BucketBrazil,
             @"Antarctica/Davis" : LVCAmazonS3BucketBrazil,
             @"Antarctica/DumontDUrville" : LVCAmazonS3BucketBrazil,
             @"Antarctica/Macquarie" : LVCAmazonS3BucketBrazil,
             @"Antarctica/Mawson" : LVCAmazonS3BucketBrazil,
             @"Antarctica/McMurdo" : LVCAmazonS3BucketBrazil,
             @"Antarctica/Palmer" : LVCAmazonS3BucketBrazil,
             @"Antarctica/Rothera" : LVCAmazonS3BucketBrazil,
             @"Antarctica/South_Pole" : LVCAmazonS3BucketBrazil,
             @"Antarctica/Syowa" : LVCAmazonS3BucketBrazil,
             @"Antarctica/Vostok" : LVCAmazonS3BucketBrazil,
             @"Arctic/Longyearbyen" : LVCAmazonS3BucketBrazil,
             @"Asia/Aden" : LVCAmazonS3BucketSingapore,
             @"Asia/Almaty" : LVCAmazonS3BucketSingapore,
             @"Asia/Amman" : LVCAmazonS3BucketSingapore,
             @"Asia/Anadyr" : LVCAmazonS3BucketSingapore,
             @"Asia/Aqtau" : LVCAmazonS3BucketSingapore,
             @"Asia/Aqtobe" : LVCAmazonS3BucketSingapore,
             @"Asia/Ashgabat" : LVCAmazonS3BucketSingapore,
             @"Asia/Baghdad" : LVCAmazonS3BucketSingapore,
             @"Asia/Bahrain" : LVCAmazonS3BucketSingapore,
             @"Asia/Baku" : LVCAmazonS3BucketSingapore,
             @"Asia/Bangkok" : LVCAmazonS3BucketSingapore,
             @"Asia/Beirut" : LVCAmazonS3BucketSingapore,
             @"Asia/Bishkek" : LVCAmazonS3BucketSingapore,
             @"Asia/Brunei" : LVCAmazonS3BucketSingapore,
             @"Asia/Choibalsan" : LVCAmazonS3BucketSingapore,
             @"Asia/Chongqing" : LVCAmazonS3BucketSingapore,
             @"Asia/Colombo" : LVCAmazonS3BucketSingapore,
             @"Asia/Damascus" : LVCAmazonS3BucketSingapore,
             @"Asia/Dhaka" : LVCAmazonS3BucketSingapore,
             @"Asia/Dili" : LVCAmazonS3BucketSingapore,
             @"Asia/Dubai" : LVCAmazonS3BucketSingapore,
             @"Asia/Dushanbe" : LVCAmazonS3BucketSingapore,
             @"Asia/Gaza" : LVCAmazonS3BucketSingapore,
             @"Asia/Harbin" : LVCAmazonS3BucketSingapore,
             @"Asia/Hebron" : LVCAmazonS3BucketSingapore,
             @"Asia/Ho_Chi_Minh" : LVCAmazonS3BucketSingapore,
             @"Asia/Hong_Kong" : LVCAmazonS3BucketSingapore,
             @"Asia/Hovd" : LVCAmazonS3BucketSingapore,
             @"Asia/Irkutsk" : LVCAmazonS3BucketSingapore,
             @"Asia/Jakarta" : LVCAmazonS3BucketSingapore,
             @"Asia/Jayapura" : LVCAmazonS3BucketSingapore,
             @"Asia/Jerusalem" : LVCAmazonS3BucketSingapore,
             @"Asia/Kabul" : LVCAmazonS3BucketSingapore,
             @"Asia/Kamchatka" : LVCAmazonS3BucketSingapore,
             @"Asia/Karachi" : LVCAmazonS3BucketSingapore,
             @"Asia/Kashgar" : LVCAmazonS3BucketSingapore,
             @"Asia/Kathmandu" : LVCAmazonS3BucketSingapore,
             @"Asia/Katmandu" : LVCAmazonS3BucketSingapore,
             @"Asia/Khandyga" : LVCAmazonS3BucketSingapore,
             @"Asia/Kolkata" : LVCAmazonS3BucketSingapore,
             @"Asia/Krasnoyarsk" : LVCAmazonS3BucketSingapore,
             @"Asia/Kuala_Lumpur" : LVCAmazonS3BucketSingapore,
             @"Asia/Kuching" : LVCAmazonS3BucketSingapore,
             @"Asia/Kuwait" : LVCAmazonS3BucketSingapore,
             @"Asia/Macau" : LVCAmazonS3BucketSingapore,
             @"Asia/Magadan" : LVCAmazonS3BucketSingapore,
             @"Asia/Makassar" : LVCAmazonS3BucketSingapore,
             @"Asia/Manila" : LVCAmazonS3BucketSingapore,
             @"Asia/Muscat" : LVCAmazonS3BucketSingapore,
             @"Asia/Nicosia" : LVCAmazonS3BucketSingapore,
             @"Asia/Novokuznetsk" : LVCAmazonS3BucketSingapore,
             @"Asia/Novosibirsk" : LVCAmazonS3BucketSingapore,
             @"Asia/Omsk" : LVCAmazonS3BucketSingapore,
             @"Asia/Oral" : LVCAmazonS3BucketSingapore,
             @"Asia/Phnom_Penh" : LVCAmazonS3BucketSingapore,
             @"Asia/Pontianak" : LVCAmazonS3BucketSingapore,
             @"Asia/Pyongyang" : LVCAmazonS3BucketSingapore,
             @"Asia/Qatar" : LVCAmazonS3BucketSingapore,
             @"Asia/Qyzylorda" : LVCAmazonS3BucketSingapore,
             @"Asia/Rangoon" : LVCAmazonS3BucketSingapore,
             @"Asia/Riyadh" : LVCAmazonS3BucketSingapore,
             @"Asia/Sakhalin" : LVCAmazonS3BucketSingapore,
             @"Asia/Samarkand" : LVCAmazonS3BucketSingapore,
             @"Asia/Seoul" : LVCAmazonS3BucketJapan,
             @"Asia/Shanghai" : LVCAmazonS3BucketSingapore,
             @"Asia/Singapore" : LVCAmazonS3BucketSingapore,
             @"Asia/Taipei" : LVCAmazonS3BucketSingapore,
             @"Asia/Tashkent" : LVCAmazonS3BucketSingapore,
             @"Asia/Tbilisi" : LVCAmazonS3BucketSingapore,
             @"Asia/Tehran" : LVCAmazonS3BucketSingapore,
             @"Asia/Thimphu" : LVCAmazonS3BucketSingapore,
             @"Asia/Tokyo" : LVCAmazonS3BucketJapan,
             @"Asia/Ulaanbaatar" : LVCAmazonS3BucketSingapore,
             @"Asia/Urumqi" : LVCAmazonS3BucketSingapore,
             @"Asia/Ust-Nera" : LVCAmazonS3BucketSingapore,
             @"Asia/Vientiane" : LVCAmazonS3BucketSingapore,
             @"Asia/Vladivostok" : LVCAmazonS3BucketSingapore,
             @"Asia/Yakutsk" : LVCAmazonS3BucketSingapore,
             @"Asia/Yekaterinburg" : LVCAmazonS3BucketSingapore,
             @"Asia/Yerevan" : LVCAmazonS3BucketSingapore,
             @"Atlantic/Azores" : LVCAmazonS3BucketDefault,
             @"Atlantic/Bermuda" : LVCAmazonS3BucketDefault,
             @"Atlantic/Canary" : LVCAmazonS3BucketEU,
             @"Atlantic/Cape_Verde" : LVCAmazonS3BucketEU,
             @"Atlantic/Faroe" : LVCAmazonS3BucketEU,
             @"Atlantic/Madeira" : LVCAmazonS3BucketEU,
             @"Atlantic/Reykjavik" : LVCAmazonS3BucketEU,
             @"Atlantic/South_Georgia" : LVCAmazonS3BucketBrazil,
             @"Atlantic/St_Helena" : LVCAmazonS3BucketEU,
             @"Atlantic/Stanley" : LVCAmazonS3BucketBrazil,
             @"Australia/Adelaide" : LVCAmazonS3BucketAustralia,
             @"Australia/Brisbane" : LVCAmazonS3BucketAustralia,
             @"Australia/Broken_Hill" : LVCAmazonS3BucketAustralia,
             @"Australia/Currie" : LVCAmazonS3BucketAustralia,
             @"Australia/Darwin" : LVCAmazonS3BucketAustralia,
             @"Australia/Eucla" : LVCAmazonS3BucketAustralia,
             @"Australia/Hobart" : LVCAmazonS3BucketAustralia,
             @"Australia/Lindeman" : LVCAmazonS3BucketAustralia,
             @"Australia/Lord_Howe" : LVCAmazonS3BucketAustralia,
             @"Australia/Melbourne" : LVCAmazonS3BucketAustralia,
             @"Australia/Perth" : LVCAmazonS3BucketAustralia,
             @"Australia/Sydney" : LVCAmazonS3BucketAustralia,
             @"Europe/Amsterdam" : LVCAmazonS3BucketEU,
             @"Europe/Andorra" : LVCAmazonS3BucketEU,
             @"Europe/Athens" : LVCAmazonS3BucketEU,
             @"Europe/Belgrade" : LVCAmazonS3BucketEU,
             @"Europe/Berlin" : LVCAmazonS3BucketEU,
             @"Europe/Bratislava" : LVCAmazonS3BucketEU,
             @"Europe/Brussels" : LVCAmazonS3BucketEU,
             @"Europe/Bucharest" : LVCAmazonS3BucketEU,
             @"Europe/Budapest" : LVCAmazonS3BucketEU,
             @"Europe/Busingen" : LVCAmazonS3BucketEU,
             @"Europe/Chisinau" : LVCAmazonS3BucketEU,
             @"Europe/Copenhagen" : LVCAmazonS3BucketEU,
             @"Europe/Dublin" : LVCAmazonS3BucketEU,
             @"Europe/Gibraltar" : LVCAmazonS3BucketEU,
             @"Europe/Guernsey" : LVCAmazonS3BucketEU,
             @"Europe/Helsinki" : LVCAmazonS3BucketEU,
             @"Europe/Isle_of_Man" : LVCAmazonS3BucketEU,
             @"Europe/Istanbul" : LVCAmazonS3BucketEU,
             @"Europe/Jersey" : LVCAmazonS3BucketEU,
             @"Europe/Kaliningrad" : LVCAmazonS3BucketEU,
             @"Europe/Kiev" : LVCAmazonS3BucketEU,
             @"Europe/Lisbon" : LVCAmazonS3BucketEU,
             @"Europe/Ljubljana" : LVCAmazonS3BucketEU,
             @"Europe/London" : LVCAmazonS3BucketEU,
             @"Europe/Luxembourg" : LVCAmazonS3BucketEU,
             @"Europe/Madrid" : LVCAmazonS3BucketEU,
             @"Europe/Malta" : LVCAmazonS3BucketEU,
             @"Europe/Mariehamn" : LVCAmazonS3BucketEU,
             @"Europe/Minsk" : LVCAmazonS3BucketEU,
             @"Europe/Monaco" : LVCAmazonS3BucketEU,
             @"Europe/Moscow" : LVCAmazonS3BucketEU,
             @"Europe/Oslo" : LVCAmazonS3BucketEU,
             @"Europe/Paris" : LVCAmazonS3BucketEU,
             @"Europe/Podgorica" : LVCAmazonS3BucketEU,
             @"Europe/Prague" : LVCAmazonS3BucketEU,
             @"Europe/Riga" : LVCAmazonS3BucketEU,
             @"Europe/Rome" : LVCAmazonS3BucketEU,
             @"Europe/Samara" : LVCAmazonS3BucketEU,
             @"Europe/San_Marino" : LVCAmazonS3BucketEU,
             @"Europe/Sarajevo" : LVCAmazonS3BucketEU,
             @"Europe/Simferopol" : LVCAmazonS3BucketEU,
             @"Europe/Skopje" : LVCAmazonS3BucketEU,
             @"Europe/Sofia" : LVCAmazonS3BucketEU,
             @"Europe/Stockholm" : LVCAmazonS3BucketEU,
             @"Europe/Tallinn" : LVCAmazonS3BucketEU,
             @"Europe/Tirane" : LVCAmazonS3BucketEU,
             @"Europe/Uzhgorod" : LVCAmazonS3BucketEU,
             @"Europe/Vaduz" : LVCAmazonS3BucketEU,
             @"Europe/Vatican" : LVCAmazonS3BucketEU,
             @"Europe/Vienna" : LVCAmazonS3BucketEU,
             @"Europe/Vilnius" : LVCAmazonS3BucketEU,
             @"Europe/Volgograd" : LVCAmazonS3BucketEU,
             @"Europe/Warsaw" : LVCAmazonS3BucketEU,
             @"Europe/Zagreb" : LVCAmazonS3BucketEU,
             @"Europe/Zaporozhye" : LVCAmazonS3BucketEU,
             @"Europe/Zurich" : LVCAmazonS3BucketEU,
             @"GMT" : LVCAmazonS3BucketEU,
             @"Indian/Antananarivo" : LVCAmazonS3BucketSingapore,
             @"Indian/Chagos" : LVCAmazonS3BucketSingapore,
             @"Indian/Christmas" : LVCAmazonS3BucketSingapore,
             @"Indian/Cocos" : LVCAmazonS3BucketSingapore,
             @"Indian/Comoro" : LVCAmazonS3BucketSingapore,
             @"Indian/Kerguelen" : LVCAmazonS3BucketSingapore,
             @"Indian/Mahe" : LVCAmazonS3BucketSingapore,
             @"Indian/Maldives" : LVCAmazonS3BucketSingapore,
             @"Indian/Mauritius" : LVCAmazonS3BucketSingapore,
             @"Indian/Mayotte" : LVCAmazonS3BucketSingapore,
             @"Indian/Reunion" : LVCAmazonS3BucketSingapore,
             @"Pacific/Apia" : LVCAmazonS3BucketJapan,
             @"Pacific/Auckland" : LVCAmazonS3BucketJapan,
             @"Pacific/Chatham" : LVCAmazonS3BucketJapan,
             @"Pacific/Chuuk" : LVCAmazonS3BucketJapan,
             @"Pacific/Easter" : LVCAmazonS3BucketJapan,
             @"Pacific/Efate" : LVCAmazonS3BucketJapan,
             @"Pacific/Enderbury" : LVCAmazonS3BucketJapan,
             @"Pacific/Fakaofo" : LVCAmazonS3BucketJapan,
             @"Pacific/Fiji" : LVCAmazonS3BucketJapan,
             @"Pacific/Funafuti" : LVCAmazonS3BucketJapan,
             @"Pacific/Galapagos" : LVCAmazonS3BucketJapan,
             @"Pacific/Gambier" : LVCAmazonS3BucketJapan,
             @"Pacific/Guadalcanal" : LVCAmazonS3BucketJapan,
             @"Pacific/Guam" : LVCAmazonS3BucketJapan,
             @"Pacific/Honolulu" : LVCAmazonS3BucketWest,
             @"Pacific/Johnston" : LVCAmazonS3BucketJapan,
             @"Pacific/Kiritimati" : LVCAmazonS3BucketJapan,
             @"Pacific/Kosrae" : LVCAmazonS3BucketJapan,
             @"Pacific/Kwajalein" : LVCAmazonS3BucketJapan,
             @"Pacific/Majuro" : LVCAmazonS3BucketJapan,
             @"Pacific/Marquesas" : LVCAmazonS3BucketJapan,
             @"Pacific/Midway" : LVCAmazonS3BucketJapan,
             @"Pacific/Nauru" : LVCAmazonS3BucketJapan,
             @"Pacific/Niue" : LVCAmazonS3BucketJapan,
             @"Pacific/Norfolk" : LVCAmazonS3BucketJapan,
             @"Pacific/Noumea" : LVCAmazonS3BucketJapan,
             @"Pacific/Pago_Pago" : LVCAmazonS3BucketJapan,
             @"Pacific/Palau" : LVCAmazonS3BucketJapan,
             @"Pacific/Pitcairn" : LVCAmazonS3BucketJapan,
             @"Pacific/Pohnpei" : LVCAmazonS3BucketJapan,
             @"Pacific/Ponape" : LVCAmazonS3BucketJapan,
             @"Pacific/Port_Moresby" : LVCAmazonS3BucketJapan,
             @"Pacific/Rarotonga" : LVCAmazonS3BucketJapan,
             @"Pacific/Saipan" : LVCAmazonS3BucketJapan,
             @"Pacific/Tahiti" : LVCAmazonS3BucketJapan,
             @"Pacific/Tarawa" : LVCAmazonS3BucketJapan,
             @"Pacific/Tongatapu" : LVCAmazonS3BucketJapan,
             @"Pacific/Truk" : LVCAmazonS3BucketJapan,
             @"Pacific/Wake" : LVCAmazonS3BucketJapan,
             @"Pacific/Wallis": LVCAmazonS3BucketJapan};
}

@implementation LVCAmazonS3Bucket

+ (NSURL *)baseURLForLocalTimezone
{
    return [self baseURLForTimezone:[NSTimeZone localTimeZone]];
}


+ (NSURL *)baseURLForTimezone:(NSTimeZone *)timeZone
{
    NSString *bucket = nil;
    if (timeZone.name.length > 0) {
        bucket = timeZoneIDToHost()[timeZone.name];
    }
    bucket = bucket ?: LVCAmazonS3BucketDefault;
    return [NSURL URLWithString:[NSString stringWithFormat:@"https://%@.s3.amazonaws.com", bucket]];
}

@end
