//
//  LVCAmazonS3Bucket.m
//  LayerVaultAPIClient
//
//  Created by Matt Thomas on 2/13/14.
//  Copyright (c) 2014 LayerVault. All rights reserved.
//

#import "LVCAmazonS3Bucket.h"

static NSDictionary *timeZoneIDToHost(void)
{
    return @{@"Africa/Abidjan" : @"omnivore-scratch-eu",
             @"Africa/Accra" : @"omnivore-scratch-eu",
             @"Africa/Addis_Ababa" : @"omnivore-scratch-eu",
             @"Africa/Algiers" : @"omnivore-scratch-eu",
             @"Africa/Asmara" : @"omnivore-scratch-eu",
             @"Africa/Bamako" : @"omnivore-scratch-eu",
             @"Africa/Bangui" : @"omnivore-scratch-eu",
             @"Africa/Banjul" : @"omnivore-scratch-eu",
             @"Africa/Bissau" : @"omnivore-scratch-eu",
             @"Africa/Blantyre" : @"omnivore-scratch-eu",
             @"Africa/Brazzaville" : @"omnivore-scratch-eu",
             @"Africa/Bujumbura" : @"omnivore-scratch-eu",
             @"Africa/Cairo" : @"omnivore-scratch-eu",
             @"Africa/Casablanca" : @"omnivore-scratch-eu",
             @"Africa/Ceuta" : @"omnivore-scratch-eu",
             @"Africa/Conakry" : @"omnivore-scratch-eu",
             @"Africa/Dakar" : @"omnivore-scratch-eu",
             @"Africa/Dar_es_Salaam" : @"omnivore-scratch-eu",
             @"Africa/Djibouti" : @"omnivore-scratch-eu",
             @"Africa/Douala" : @"omnivore-scratch-eu",
             @"Africa/El_Aaiun" : @"omnivore-scratch-eu",
             @"Africa/Freetown" : @"omnivore-scratch-eu",
             @"Africa/Gaborone" : @"omnivore-scratch-eu",
             @"Africa/Harare" : @"omnivore-scratch-eu",
             @"Africa/Johannesburg" : @"omnivore-scratch-eu",
             @"Africa/Juba" : @"omnivore-scratch-eu",
             @"America/St_Kitts" : @"omnivore-scratch",
             @"America/St_Lucia" : @"omnivore-scratch",
             @"America/St_Thomas" : @"omnivore-scratch",
             @"America/St_Vincent" : @"omnivore-scratch",
             @"America/Swift_Current" : @"omnivore-scratch-west",
             @"America/Tegucigalpa" : @"omnivore-scratch-west",
             @"America/Thule" : @"omnivore-scratch",
             @"America/Thunder_Bay" : @"omnivore-scratch",
             @"America/Tijuana" : @"omnivore-scratch-west",
             @"America/Toronto" : @"omnivore-scratch",
             @"America/Tortola" : @"omnivore-scratch",
             @"America/Vancouver" : @"omnivore-scratch",
             @"America/Whitehorse" : @"omnivore-scratch-west",
             @"America/Winnipeg" : @"omnivore-scratch",
             @"America/Yakutat" : @"omnivore-scratch-west",
             @"America/Yellowknife" : @"omnivore-scratch-west",
             @"Antarctica/Casey" : @"omnivore-scratch-brazil",
             @"Antarctica/Davis" : @"omnivore-scratch-brazil",
             @"Antarctica/DumontDUrville" : @"omnivore-scratch-brazil",
             @"Antarctica/Macquarie" : @"omnivore-scratch-brazil",
             @"Antarctica/Mawson" : @"omnivore-scratch-brazil",
             @"Antarctica/McMurdo" : @"omnivore-scratch-brazil",
             @"Antarctica/Palmer" : @"omnivore-scratch-brazil",
             @"Antarctica/Rothera" : @"omnivore-scratch-brazil",
             @"Antarctica/South_Pole" : @"omnivore-scratch-brazil",
             @"Antarctica/Syowa" : @"omnivore-scratch-brazil",
             @"Antarctica/Vostok" : @"omnivore-scratch-brazil",
             @"Arctic/Longyearbyen" : @"omnivore-scratch-brazil",
             @"Asia/Aden" : @"omnivore-scratch-singapore",
             @"Asia/Almaty" : @"omnivore-scratch-singapore",
             @"Asia/Amman" : @"omnivore-scratch-singapore",
             @"Asia/Anadyr" : @"omnivore-scratch-singapore",
             @"Asia/Aqtau" : @"omnivore-scratch-singapore",
             @"Asia/Aqtobe" : @"omnivore-scratch-singapore",
             @"Asia/Ashgabat" : @"omnivore-scratch-singapore",
             @"Asia/Baghdad" : @"omnivore-scratch-singapore",
             @"Asia/Bahrain" : @"omnivore-scratch-singapore",
             @"Asia/Baku" : @"omnivore-scratch-singapore",
             @"Asia/Bangkok" : @"omnivore-scratch-singapore",
             @"Asia/Beirut" : @"omnivore-scratch-singapore",
             @"Asia/Bishkek" : @"omnivore-scratch-singapore",
             @"Asia/Brunei" : @"omnivore-scratch-singapore",
             @"Asia/Choibalsan" : @"omnivore-scratch-singapore",
             @"Asia/Chongqing" : @"omnivore-scratch-singapore",
             @"Asia/Colombo" : @"omnivore-scratch-singapore",
             @"Asia/Damascus" : @"omnivore-scratch-singapore",
             @"Asia/Dhaka" : @"omnivore-scratch-singapore",
             @"Asia/Dili" : @"omnivore-scratch-singapore",
             @"Asia/Dubai" : @"omnivore-scratch-singapore",
             @"Asia/Dushanbe" : @"omnivore-scratch-singapore",
             @"Asia/Gaza" : @"omnivore-scratch-singapore",
             @"Asia/Harbin" : @"omnivore-scratch-singapore",
             @"Asia/Hebron" : @"omnivore-scratch-singapore",
             @"Asia/Ho_Chi_Minh" : @"omnivore-scratch-singapore",
             @"Asia/Hong_Kong" : @"omnivore-scratch-singapore",
             @"Asia/Hovd" : @"omnivore-scratch-singapore",
             @"Asia/Irkutsk" : @"omnivore-scratch-singapore",
             @"Asia/Jakarta" : @"omnivore-scratch-singapore",
             @"Asia/Jayapura" : @"omnivore-scratch-singapore",
             @"Asia/Jerusalem" : @"omnivore-scratch-singapore",
             @"Asia/Kabul" : @"omnivore-scratch-singapore",
             @"Asia/Kamchatka" : @"omnivore-scratch-singapore",
             @"Asia/Karachi" : @"omnivore-scratch-singapore",
             @"Asia/Kashgar" : @"omnivore-scratch-singapore",
             @"Asia/Kathmandu" : @"omnivore-scratch-singapore",
             @"Asia/Katmandu" : @"omnivore-scratch-singapore",
             @"Asia/Khandyga" : @"omnivore-scratch-singapore",
             @"Asia/Kolkata" : @"omnivore-scratch-singapore",
             @"Asia/Krasnoyarsk" : @"omnivore-scratch-singapore",
             @"Asia/Kuala_Lumpur" : @"omnivore-scratch-singapore",
             @"Asia/Kuching" : @"omnivore-scratch-singapore",
             @"Asia/Kuwait" : @"omnivore-scratch-singapore",
             @"Asia/Macau" : @"omnivore-scratch-singapore",
             @"Asia/Magadan" : @"omnivore-scratch-singapore",
             @"Asia/Makassar" : @"omnivore-scratch-singapore",
             @"Asia/Manila" : @"omnivore-scratch-singapore",
             @"Asia/Muscat" : @"omnivore-scratch-singapore",
             @"Asia/Nicosia" : @"omnivore-scratch-singapore",
             @"Asia/Novokuznetsk" : @"omnivore-scratch-singapore",
             @"Asia/Novosibirsk" : @"omnivore-scratch-singapore",
             @"Asia/Omsk" : @"omnivore-scratch-singapore",
             @"Asia/Oral" : @"omnivore-scratch-singapore",
             @"Asia/Phnom_Penh" : @"omnivore-scratch-singapore",
             @"Asia/Pontianak" : @"omnivore-scratch-singapore",
             @"Asia/Pyongyang" : @"omnivore-scratch-singapore",
             @"Asia/Qatar" : @"omnivore-scratch-singapore",
             @"Asia/Qyzylorda" : @"omnivore-scratch-singapore",
             @"Asia/Rangoon" : @"omnivore-scratch-singapore",
             @"Asia/Riyadh" : @"omnivore-scratch-singapore",
             @"Asia/Sakhalin" : @"omnivore-scratch-singapore",
             @"Asia/Samarkand" : @"omnivore-scratch-singapore",
             @"Asia/Seoul" : @"omnivore-scratch-japan",
             @"Asia/Shanghai" : @"omnivore-scratch-singapore",
             @"Asia/Singapore" : @"omnivore-scratch-singapore",
             @"Asia/Taipei" : @"omnivore-scratch-singapore",
             @"Asia/Tashkent" : @"omnivore-scratch-singapore",
             @"Asia/Tbilisi" : @"omnivore-scratch-singapore",
             @"Asia/Tehran" : @"omnivore-scratch-singapore",
             @"Asia/Thimphu" : @"omnivore-scratch-singapore",
             @"Asia/Tokyo" : @"omnivore-scratch-japan",
             @"Asia/Ulaanbaatar" : @"omnivore-scratch-singapore",
             @"Asia/Urumqi" : @"omnivore-scratch-singapore",
             @"Asia/Ust-Nera" : @"omnivore-scratch-singapore",
             @"Asia/Vientiane" : @"omnivore-scratch-singapore",
             @"Asia/Vladivostok" : @"omnivore-scratch-singapore",
             @"Asia/Yakutsk" : @"omnivore-scratch-singapore",
             @"Asia/Yekaterinburg" : @"omnivore-scratch-singapore",
             @"Asia/Yerevan" : @"omnivore-scratch-singapore",
             @"Atlantic/Azores" : @"omnivore-scratch",
             @"Atlantic/Bermuda" : @"omnivore-scratch",
             @"Atlantic/Canary" : @"omnivore-scratch-eu",
             @"Atlantic/Cape_Verde" : @"omnivore-scratch-eu",
             @"Atlantic/Faroe" : @"omnivore-scratch-eu",
             @"Atlantic/Madeira" : @"omnivore-scratch-eu",
             @"Atlantic/Reykjavik" : @"omnivore-scratch-eu",
             @"Atlantic/South_Georgia" : @"omnivore-scratch-brazil",
             @"Atlantic/St_Helena" : @"omnivore-scratch-eu",
             @"Atlantic/Stanley" : @"omnivore-scratch-brazil",
             @"Australia/Adelaide" : @"omnivore-scratch-australia",
             @"Australia/Brisbane" : @"omnivore-scratch-australia",
             @"Australia/Broken_Hill" : @"omnivore-scratch-australia",
             @"Australia/Currie" : @"omnivore-scratch-australia",
             @"Australia/Darwin" : @"omnivore-scratch-australia",
             @"Australia/Eucla" : @"omnivore-scratch-australia",
             @"Australia/Hobart" : @"omnivore-scratch-australia",
             @"Australia/Lindeman" : @"omnivore-scratch-australia",
             @"Australia/Lord_Howe" : @"omnivore-scratch-australia",
             @"Australia/Melbourne" : @"omnivore-scratch-australia",
             @"Australia/Perth" : @"omnivore-scratch-australia",
             @"Australia/Sydney" : @"omnivore-scratch-australia",
             @"Europe/Amsterdam" : @"omnivore-scratch-eu",
             @"Europe/Andorra" : @"omnivore-scratch-eu",
             @"Europe/Athens" : @"omnivore-scratch-eu",
             @"Europe/Belgrade" : @"omnivore-scratch-eu",
             @"Europe/Berlin" : @"omnivore-scratch-eu",
             @"Europe/Bratislava" : @"omnivore-scratch-eu",
             @"Europe/Brussels" : @"omnivore-scratch-eu",
             @"Europe/Bucharest" : @"omnivore-scratch-eu",
             @"Europe/Budapest" : @"omnivore-scratch-eu",
             @"Europe/Busingen" : @"omnivore-scratch-eu",
             @"Europe/Chisinau" : @"omnivore-scratch-eu",
             @"Europe/Copenhagen" : @"omnivore-scratch-eu",
             @"Europe/Dublin" : @"omnivore-scratch-eu",
             @"Europe/Gibraltar" : @"omnivore-scratch-eu",
             @"Europe/Guernsey" : @"omnivore-scratch-eu",
             @"Europe/Helsinki" : @"omnivore-scratch-eu",
             @"Europe/Isle_of_Man" : @"omnivore-scratch-eu",
             @"Europe/Istanbul" : @"omnivore-scratch-eu",
             @"Europe/Jersey" : @"omnivore-scratch-eu",
             @"Europe/Kaliningrad" : @"omnivore-scratch-eu",
             @"Europe/Kiev" : @"omnivore-scratch-eu",
             @"Europe/Lisbon" : @"omnivore-scratch-eu",
             @"Europe/Ljubljana" : @"omnivore-scratch-eu",
             @"Europe/London" : @"omnivore-scratch-eu",
             @"Europe/Luxembourg" : @"omnivore-scratch-eu",
             @"Europe/Madrid" : @"omnivore-scratch-eu",
             @"Europe/Malta" : @"omnivore-scratch-eu",
             @"Europe/Mariehamn" : @"omnivore-scratch-eu",
             @"Europe/Minsk" : @"omnivore-scratch-eu",
             @"Europe/Monaco" : @"omnivore-scratch-eu",
             @"Europe/Moscow" : @"omnivore-scratch-eu",
             @"Europe/Oslo" : @"omnivore-scratch-eu",
             @"Europe/Paris" : @"omnivore-scratch-eu",
             @"Europe/Podgorica" : @"omnivore-scratch-eu",
             @"Europe/Prague" : @"omnivore-scratch-eu",
             @"Europe/Riga" : @"omnivore-scratch-eu",
             @"Europe/Rome" : @"omnivore-scratch-eu",
             @"Europe/Samara" : @"omnivore-scratch-eu",
             @"Europe/San_Marino" : @"omnivore-scratch-eu",
             @"Europe/Sarajevo" : @"omnivore-scratch-eu",
             @"Europe/Simferopol" : @"omnivore-scratch-eu",
             @"Europe/Skopje" : @"omnivore-scratch-eu",
             @"Europe/Sofia" : @"omnivore-scratch-eu",
             @"Europe/Stockholm" : @"omnivore-scratch-eu",
             @"Europe/Tallinn" : @"omnivore-scratch-eu",
             @"Europe/Tirane" : @"omnivore-scratch-eu",
             @"Europe/Uzhgorod" : @"omnivore-scratch-eu",
             @"Europe/Vaduz" : @"omnivore-scratch-eu",
             @"Europe/Vatican" : @"omnivore-scratch-eu",
             @"Europe/Vienna" : @"omnivore-scratch-eu",
             @"Europe/Vilnius" : @"omnivore-scratch-eu",
             @"Europe/Volgograd" : @"omnivore-scratch-eu",
             @"Europe/Warsaw" : @"omnivore-scratch-eu",
             @"Europe/Zagreb" : @"omnivore-scratch-eu",
             @"Europe/Zaporozhye" : @"omnivore-scratch-eu",
             @"Europe/Zurich" : @"omnivore-scratch-eu",
             @"GMT" : @"omnivore-scratch-eu",
             @"Indian/Antananarivo" : @"omnivore-scratch-singapore",
             @"Indian/Chagos" : @"omnivore-scratch-singapore",
             @"Indian/Christmas" : @"omnivore-scratch-singapore",
             @"Indian/Cocos" : @"omnivore-scratch-singapore",
             @"Indian/Comoro" : @"omnivore-scratch-singapore",
             @"Indian/Kerguelen" : @"omnivore-scratch-singapore",
             @"Indian/Mahe" : @"omnivore-scratch-singapore",
             @"Indian/Maldives" : @"omnivore-scratch-singapore",
             @"Indian/Mauritius" : @"omnivore-scratch-singapore",
             @"Indian/Mayotte" : @"omnivore-scratch-singapore",
             @"Indian/Reunion" : @"omnivore-scratch-singapore",
             @"Pacific/Apia" : @"omnivore-scratch-japan",
             @"Pacific/Auckland" : @"omnivore-scratch-japan",
             @"Pacific/Chatham" : @"omnivore-scratch-japan",
             @"Pacific/Chuuk" : @"omnivore-scratch-japan",
             @"Pacific/Easter" : @"omnivore-scratch-japan",
             @"Pacific/Efate" : @"omnivore-scratch-japan",
             @"Pacific/Enderbury" : @"omnivore-scratch-japan",
             @"Pacific/Fakaofo" : @"omnivore-scratch-japan",
             @"Pacific/Fiji" : @"omnivore-scratch-japan",
             @"Pacific/Funafuti" : @"omnivore-scratch-japan",
             @"Pacific/Galapagos" : @"omnivore-scratch-japan",
             @"Pacific/Gambier" : @"omnivore-scratch-japan",
             @"Pacific/Guadalcanal" : @"omnivore-scratch-japan",
             @"Pacific/Guam" : @"omnivore-scratch-japan",
             @"Pacific/Honolulu" : @"omnivore-scratch-west",
             @"Pacific/Johnston" : @"omnivore-scratch-japan",
             @"Pacific/Kiritimati" : @"omnivore-scratch-japan",
             @"Pacific/Kosrae" : @"omnivore-scratch-japan",
             @"Pacific/Kwajalein" : @"omnivore-scratch-japan",
             @"Pacific/Majuro" : @"omnivore-scratch-japan",
             @"Pacific/Marquesas" : @"omnivore-scratch-japan",
             @"Pacific/Midway" : @"omnivore-scratch-japan",
             @"Pacific/Nauru" : @"omnivore-scratch-japan",
             @"Pacific/Niue" : @"omnivore-scratch-japan",
             @"Pacific/Norfolk" : @"omnivore-scratch-japan",
             @"Pacific/Noumea" : @"omnivore-scratch-japan",
             @"Pacific/Pago_Pago" : @"omnivore-scratch-japan",
             @"Pacific/Palau" : @"omnivore-scratch-japan",
             @"Pacific/Pitcairn" : @"omnivore-scratch-japan",
             @"Pacific/Pohnpei" : @"omnivore-scratch-japan",
             @"Pacific/Ponape" : @"omnivore-scratch-japan",
             @"Pacific/Port_Moresby" : @"omnivore-scratch-japan",
             @"Pacific/Rarotonga" : @"omnivore-scratch-japan",
             @"Pacific/Saipan" : @"omnivore-scratch-japan",
             @"Pacific/Tahiti" : @"omnivore-scratch-japan",
             @"Pacific/Tarawa" : @"omnivore-scratch-japan",
             @"Pacific/Tongatapu" : @"omnivore-scratch-japan",
             @"Pacific/Truk" : @"omnivore-scratch-japan",
             @"Pacific/Wake" : @"omnivore-scratch-japan",
             @"Pacific/Wallis": @"omnivore-scratch-japan"};
}

@implementation LVCAmazonS3Bucket

+ (NSURL *)baseURLForLocalTimezone
{
    return [self baseURLForTimezone:[NSTimeZone localTimeZone]];
}


+ (NSURL *)baseURLForTimezone:(NSTimeZone *)timeZone
{
    NSString *bucket = nil;
    if (timeZone.name.length > 0) {
        bucket = timeZoneIDToHost()[timeZone.name];
    }
    bucket = bucket ?: @"omnivore-scratch";
    return [NSURL URLWithString:[NSString stringWithFormat:@"https://%@.s3.amazonaws.com", bucket]];
}

@end
